### ISSUE TITLE
error in browserify vector

### ISSUE THREAD

**Issue by kenany** [max-mapper/hexbin#10]
I'm seeing the following when I open http://hexb.in/vector/browserify.svg in chromium:

![](https://mediacru.sh/Ty5-LCvjdlqt.png)

also GitHub says it's invalid: https://github.com/maxogden/hexbin/blob/8abc1613f644ef83e5a62fcb203901f5510478fa/vector/browserify.svg

**Comment by max-mapper** [comment]
hmm...  i just tried many times to get illustrator to save a valid PDF but it won't do it. as a workaround i've included a pdf :( https://github.com/maxogden/hexbin/commit/86c1bc9d31f4d1e468b572b42d5ad59174d40d06

**Comment by kenany** [comment]
:(

**Comment by max-mapper** [comment]
sorry meant 'valid SVG' above

**Comment by max-mapper** [comment]
but yes I agree, much :(
