### ISSUE TITLE
Add links to websites

### ISSUE THREAD

**Issue by merwok** [max-mapper/hexbin#148]
At the moment, stickers link to JSON metadata that include the author name, but not a link to a chosen profile, nor a link to the thing that’s the object of the sticker.  If I want to know who made the image «move slow and make things», or when and where the CSV conf takes place, I have to search manually.

Each sticker could be a link to a chosen URL, or the metadata could include link(s).

Thanks for considering!

**Comment by pkq** [comment]
Great minds! I just proposed something similar in #199 . Several PRs include that information in the `description`, and others do so in `online_order_url`, even though that's intended for a link to order the stickers themselves. I think it'd be a great addition!
