### ISSUE TITLE
Who is in charge for the project?

### ISSUE THREAD

**Issue by siscia** [max-mapper/hexbin#167]
I am wondering if you guys need any help with the project.

Most pull request sits there without any kind of feedback, some are merged other are not.

I know we are all busy but if a help is needed I can try to help

**Comment by ha0ye** [comment]
Hi,
I got added on earlier this year and started merging some logo requests before getting busy. I don't have the requisite experience to re-build the site. Best bet is to contact Mac, I think.

**Comment by Ruxton** [comment]
After reading this issue, I hit up Max, got access and I rebuilt the site today. Any PR's that were merged that weren't displaying should now display.

Running through ALL PR's at present, starting at most recent.

**Comment by yangwao** [comment]
Thanks! :)
