### ISSUE TITLE
More stickers for sale?

### ISSUE THREAD

**Issue by StachuDotNet** [max-mapper/hexbin#22]
I really like this hexbin thing, but can currently only see 7 stickers for sale.
How can we fix this?

**Comment by max-mapper** [comment]
@StachuK1992 good question. The 7 for sale are the ones I've personally done 'runs' of with stickermule. The vector versions are included with each sticker on hexbin to allow you to print high quality stickers yourself from any vendor that supports hexagons (I have only used stickermule). 

We should find out if there are vendors that do small runs, such as 5 at a time.

**Comment by StachuDotNet** [comment]
Ok. If I find such a vendor, I'll let you know.
Just a random thought; could be possible to have a little kickstarter. Small goals, just to get started w/ batches of 50 of each kind or something. Idk. I'd throw $50 at the project to get a bunch of stickers.

**Comment by junosuarez** [comment]
teespring but for diecut stickers

**Comment by ryanj** [comment]
Should we add an 'order_workflow_url' attribute to the JSON spec, so people can link to their order form?  https://www.stickermule.com/marketplace/4611-openshift

**Comment by max-mapper** [comment]
done https://github.com/maxogden/hexbin/commit/45b10ffd4aac82a9622c320f57576c90220af6ba

**Comment by StachuDotNet** [comment]
cool
