### ISSUE TITLE
right navbar links are inconsistent across pages

### ISSUE THREAD

**Issue by jake-low** [max-mapper/hexbin#36]
Just FYI, on `index.html` the `"stickers"` item points to `stickers.html`, but on `stickers.html` the same item points to stickermule.com. Also, on `stickers.html` the `"hexb.in"` item doesn't take you back to the main page like you'd expect.

**Comment by max-mapper** [comment]
thanks for reporting! if you wanna send a PR i'd be happy to merge :) otherwise i'll put it on my todo list

**Comment by andrewdamelio** [comment]
Hi @maxogden :wave: - I believe this issue has been closed :) 

![](http://i.imgur.com/349pQPs.gif)
