### ISSUE TITLE
Differences in Hex Sticker Sizes

### ISSUE THREAD

**Issue by DamonOehlman** [max-mapper/hexbin#62]
Hey all - just wondering if anyone had noticed any variation in the size of stickers produced by @stickermule recently?  I worked pretty hard to try and get the new [CampJS VI sticker](https://www.stickermule.com/marketplace/1497-dat-data) to match the dimensions of other stickers that @maxogden had linked to on the site (e.g. [dat](https://www.stickermule.com/marketplace/1497-dat-data)).

After a couple of tries I was satisfied that I had gotten close enough:

```
CAMPJS:   1.7344" x 2"
DAT:      1.73" x 2"
```

The source vector is that I generated is exactly `1.73" x 2"` but I wasn't too worried about the slight variation post proof - I thought it would be ok (if anything the CampJS sticker would be ever so slightly too big).  That doesn't seem to be the case though with the stickers deliver being quite a smaller than what was reported (closer to `1.61" x 1.85"`).  Just wondering if this is a result of me doing something wrong or that stickermule have botched the order and I should ask them to take a look (I'm probably going to that anyway).  Just thought someone here might have had some experience with it.

**Comment by max-mapper** [comment]
In stickermules UI I always pick the 2" die-cut option and always get 2" tall stickers

**Comment by DamonOehlman** [comment]
That's definitely what I did... I wonder what went wrong.  Anyway, have emailed their support.

**Comment by DamonOehlman** [comment]
Looks like it was an issue during the cutting of the stickers.  They are sending out a new batch FOC :)

@stickermule FTW!
